#This configuration is used to register this service with Eureka Server. 
spring:
  application:
    name: zuulgateway
  profiles:
      active: dev
  cloud:
    config:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/